[project]
name = "sd-networks-info-collect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydash>=8.0.5",
    "sqlmodel>=0.0.24",
]
